# Generated by Django 3.1.7 on 2021-05-18 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('photo', models.ImageField(upload_to='photoes/students/%Y/%m/%d')),
            ],
            options={
                'unique_together': {('first_name', 'last_name', 'birthday')},
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.DateField()),
                ('field', models.CharField(choices=[('parvareshi', 'پرورشی'), ('amoozeshi', 'آموزشی'), ('pajooheshi', 'پژوهشی'), ('varzeshi', 'ورزشی')], max_length=50)),
                ('level', models.CharField(choices=[('parvareshi', 'مدرسه'), ('amoozeshi', 'ناجیه'), ('pajooheshi', 'شهر'), ('varzeshi', 'استان'), ('varzeshi', 'کشور'), ('varzeshi', 'بین الملل')], max_length=50)),
                ('dore', models.CharField(choices=[('aval', 'اول'), ('dovom', 'دوم')], max_length=50)),
                ('pic', models.ImageField(blank=True, upload_to='photoes/achievement/%Y/%m/%d')),
                ('video_link', models.CharField(blank=True, max_length=255)),
                ('detail', models.TextField(blank=True, max_length=1024)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.student')),
            ],
        ),
    ]
