# Generated by Django 3.1.7 on 2021-05-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210518_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='level',
            field=models.CharField(choices=[('madrese', 'مدرسه'), ('nahie', 'ناحیه'), ('shahr', 'شهر'), ('ostan', 'استان'), ('keshvar', 'کشور'), ('beinolmelel', 'بین الملل')], max_length=50),
        ),
    ]
