# Generated by Django 3.1.7 on 2021-05-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210524_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='dore',
            field=models.CharField(choices=[('اول', 'اول'), ('دوم', 'دوم')], max_length=50),
        ),
    ]
