# Generated by Django 3.1.7 on 2021-05-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210530_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)])),
                ('field', models.CharField(choices=[('پرورشی', 'پرورشی'), ('آموزشی', 'آموزشی'), ('پژوهشی', 'پژوهشی'), ('پژوهشی', 'ورزشی')], max_length=50)),
                ('level', models.CharField(choices=[('مدرسه', 'مدرسه'), ('ناحیه', 'ناحیه'), ('شهر', 'شهر'), ('استان', 'استان'), ('کشور', 'کشور'), ('بین الملل', 'بین الملل')], max_length=50)),
                ('dore', models.CharField(choices=[('اول', 'اول'), ('دوم', 'دوم')], max_length=50)),
                ('pic', models.ImageField(blank=True, upload_to='photoes/achievement/%Y/%m/%d')),
                ('video_link', models.CharField(blank=True, max_length=255)),
                ('detail', models.TextField(blank=True, max_length=1024)),
                ('student_confirmation', models.BooleanField(default=False)),
                ('mentor_confirmation', models.BooleanField(default=False)),
                ('manager_confirmation', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='achievement',
            name='manager_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievement',
            name='mentor_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievement',
            name='student_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
