# Generated by Django 3.1.7 on 2021-05-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20210530_1358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AchievementInstance',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='manager_confirmation',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='mentor_confirmation',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='student_confirmation',
        ),
        migrations.AddField(
            model_name='achievement',
            name='is_main',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='modify_level',
            field=models.CharField(blank=True, choices=[('student', 'student'), ('mentor', 'mentor'), ('manager', 'manager')], max_length=50),
        ),
        migrations.AddField(
            model_name='achievement',
            name='refrence_id',
            field=models.IntegerField(null=True),
        ),
    ]
