# Generated by Django 3.1.7 on 2021-05-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20210530_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
