# Generated by Django 3.1.7 on 2021-05-31 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20210531_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'permissions': (('parvareshi_mentor', 'can add parvareshi'), ('amoozeshi_mentor', 'can add amoozeshi'), ('pazhooheshi_mentor', 'can add pazhooheshi'), ('varzeshi_mentor', 'can add varzeshi'))},
        ),
    ]
