# Generated by Django 3.1.7 on 2021-05-31 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20210531_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'permissions': (('parvareshi_mentor', 'can view parvareshi'), ('amoozeshi_mentor', 'can view amoozeshi'), ('pazhooheshi_mentor', 'can view pazhooheshi'), ('varzeshi_mentor', 'can view varzeshi'))},
        ),
    ]
