# Generated by Django 3.1.7 on 2021-05-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20210531_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
