# Generated by Django 3.1.7 on 2021-06-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20210601_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
