# Generated by Django 3.1.7 on 2021-06-01 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_achievement_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='is_new',
        ),
    ]
